version: "3.7"

services:
  stat-web:
    image: nginx:alpine
    container_name: stat-web
    working_dir: /app
    volumes:
      - ./../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - stat-net

  stat-api:
    build: php
    container_name: stat-api
    volumes:
      - ./../:/app
      - stat-api-user-worker:/home/worker
    networks:
      - stat-net

  stat-storage:
    image: redis:7.0-alpine
    container_name: stat-storage
    restart: always
    volumes:
      - stat-storage:/data
    networks:
      - stat-net

volumes:
  stat-api-user-worker:
  stat-storage:

networks:
  stat-net: